export enum EMovieGenre {
    ACTION = 'action',
    MUSIC = 'music',
    SHOUNEN = 'shounen',
    ADVENTURE = 'adventure',
    ROMANCE = 'romance',
    SLICE_OF_LIFE = 'slice_of_life',
    COMEDY = 'comedy',
    SCIENCE_FICTION = 'science_fiction',
    SPORTS = 'sports',
    DRAMA = 'drama',
    SEINEN = 'seinen',
    SUPERNATURAL = 'supernatural',
    FANTASY = 'fantasy',
    SHOUJO = 'shoujo',
    THRILLER = 'thriller',
    ECCHI = 'ecchi',
    MYSTERY = 'mystery',
    HAREM = 'harem',
    HISTORICAL = 'historical',
}
