import { EAccountTitle } from '../enums/account/title.account.enum';

export const AccountTitleMapping = {
    [EAccountTitle.NEWBIE]: { title: 'Newbie', color: 'silver' },
    [EAccountTitle.BOSS]: { title: 'Boss', color: 'gradient' },
    [EAccountTitle.ADMIN]: { title: 'Admin', color: 'gradient' },
    [EAccountTitle.GODLIKE]: { title: 'Đấng toàn năng', color: 'gradient' },
    [EAccountTitle.PILLAR_MEMBER]: { title: 'Thành viên trụ cột', color: 'gradient' },
    [EAccountTitle.DAILY_STREAK]: { title: 'Chuỗi ngày hoạt động', color: 'gradient' },

    [EAccountTitle.LIEUTENANT_INTERLLIGENCE]: { title: 'Thiếu uý tình báo', color: 'blue' },
    [EAccountTitle.SECOND_LIEUTENANT_INTERLLIGENCE]: { title: 'Trung uý tình báo', color: 'green' },
    [EAccountTitle.CAPTAIN_INTERLLIGENCE]: { title: 'Đại uý tình báo', color: 'red' },
    [EAccountTitle.LIEUTENANT_COLONEL_INTERLLIGENCE]: { title: 'Thiếu tá tình báo', color: 'orange' },
    [EAccountTitle.COLONEL_INTERLLIGENCE]: { title: 'Trung tá tình báo', color: 'purple' },
    [EAccountTitle.BRIGADIER_GENERAL_INTERLLIGENCE]: { title: 'Đại tá tình báo', color: 'pink' },
    [EAccountTitle.MAJOR_GENERAL_INTERLLIGENCE]: { title: 'Thiếu tướng tình báo', color: 'yellow' },
    [EAccountTitle.LIEUTENANT_GENERAL_INTERLLIGENCE]: { title: 'Trung tướng tình báo', color: 'cyan' },
    [EAccountTitle.GENERAL_INTERLLIGENCE]: { title: 'Đại tướng tình báo', color: 'brown' },

    [EAccountTitle.SELL_OUT_TO_CAPITALISTS]: { title: 'Bán mình cho tư bản', color: 'pink' },
    [EAccountTitle.MASTER_OF_MEMES]: { title: 'Chuyên gia meme', color: 'orange' },
    [EAccountTitle.PROCRASTINATION_KING]: { title: 'Vua trì hoãn', color: 'blue' },
    [EAccountTitle.NAP_CHAMPION]: { title: 'Vô địch ngủ trưa', color: 'green' },
    [EAccountTitle.KEYBOARD_WARRIOR]: { title: 'Chiến binh bàn phím', color: 'purple' },
    [EAccountTitle.GIF_GOD]: { title: 'Thần GIF', color: 'red' },
    [EAccountTitle.MEME_LORD]: { title: 'Lão làng meme', color: 'orange' },
    [EAccountTitle.PIXEL_SLINGER]: { title: 'Xạ thủ pixel', color: 'brown' },
    [EAccountTitle.TECH_GURU]: { title: 'Thánh công nghệ', color: 'black' },
    [EAccountTitle.BUTTON_MASHER]: { title: 'Người bấm nút', color: 'gray' },
    [EAccountTitle.OVERTHINKER_EXTRAORDINAIRE]: { title: 'Kẻ suy nghĩ quá mức', color: 'cyan' },
    [EAccountTitle.COFFEE_ADDICT]: { title: 'Con nghiện cà phê', color: 'beige' },
    [EAccountTitle.NETFLIX_CONNOISSEUR]: { title: 'Chuyên gia Netflix', color: 'darkblue' },
    [EAccountTitle.SLEEPY_HEAD]: { title: 'Kẻ buồn ngủ', color: 'pink' },
    [EAccountTitle.GIF_MASTER]: { title: 'Bậc thầy GIF', color: 'gold' },
    [EAccountTitle.CHRONIC_LURKER]: { title: 'Lười nhưng luôn lặng lẽ', color: 'silver' },
    [EAccountTitle.CODE_NINJA]: { title: 'Ninja lập trình', color: 'red' },
    [EAccountTitle.MASTER_OF_SARCASM]: { title: 'Bậc thầy châm chọc', color: 'teal' },
    [EAccountTitle.BANANA_PEEL_SLIP]: { title: 'Trượt vỏ chuối', color: 'lime' },
    [EAccountTitle.SNACK_KING]: { title: 'Vua snack', color: 'green' },
    [EAccountTitle.JEDI_OF_JOKES]: { title: 'Jedi hài hước', color: 'blue' },
    [EAccountTitle.PRO_AT_NAPPING]: { title: 'Pro ngủ trưa', color: 'yellow' },
    [EAccountTitle.MEME_MACHINE]: { title: 'Máy meme', color: 'red' },
    [EAccountTitle.EMOJI_EXPERT]: { title: 'Chuyên gia emoji', color: 'purple' },
    [EAccountTitle.SPAM_MASTER]: { title: 'Bậc thầy spam', color: 'pink' },
    [EAccountTitle.FAST_FOOD_FANATIC]: { title: 'Fan thức ăn nhanh', color: 'orange' },
    [EAccountTitle.LAZINESS_CHAMPION]: { title: 'Vô địch lười biếng', color: 'brown' },
    [EAccountTitle.PIXELATED_HERO]: { title: 'Anh hùng pixel', color: 'green' },
    [EAccountTitle.SHOWER_THOUGHTS_GURU]: { title: 'Guru những suy nghĩ dưới vòi sen', color: 'cyan' },
    [EAccountTitle.WEEKEND_WARRIOR]: { title: 'Chiến binh cuối tuần', color: 'blue' },
    [EAccountTitle.LAUGHING_MACHINE]: { title: 'Máy cười', color: 'yellow' },
    [EAccountTitle.TROLL_KING]: { title: 'Vua troll', color: 'orange' },
    [EAccountTitle.DIGITAL_NOMAD]: { title: 'Du mục số', color: 'green' },
    [EAccountTitle.VIRAL_VIBES]: { title: 'Làn sóng viral', color: 'red' },
    [EAccountTitle.PIZZA_IS_LIFE]: { title: 'Pizza là cuộc sống', color: 'purple' },
    [EAccountTitle.SUSHI_SAVAGE]: { title: 'Thực khách sushi', color: 'beige' },
    [EAccountTitle.CUP_NOODLE_CONNOISSEUR]: { title: 'Chuyên gia mì ly', color: 'brown' },
    [EAccountTitle.MEME_SAVANT]: { title: 'Bậc thầy meme', color: 'gold' },
    [EAccountTitle.CAPTIAN]: { title: 'Captain', color: 'red' },
};
